- name : configuring Payment Component 
  become: yes
  hosts: payment 
  tasks:
  - name: " installing {{ item }} "
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app    
    
